import os
import sqlite3
from pathlib import Path
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request, Form, HTTPException, Depends
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles

# Import precisely matching our verified modular architecture
from source.agents import financial_agent_executor
from source.schemas import ChatRequest, ChatResponse, AgentStep


# --------------------------------------------------
# Modern Lifespan (Startup / Shutdown) Management
# --------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    print("====================================================")
    print(" Meridian Wealth Financial Agentic Node Activating...")
    print(" Core Engine: Connected via LangGraph Orchestrator")
    print(" Database: Verified targeted relative data stream")
    print(" Platform State: Operational / Ready")
    print("====================================================")
    yield
    print("Deactivating Financial Agent Node Workflow Safely.")


# Application Initialization
app = FastAPI(
    title="Financial Analyst Agent Hub",
    version="1.0.0",
    description="Enterprise ReAct Agentic RAG Platform for Meridian Wealth Partners",
    lifespan=lifespan
)


# --------------------------------------------------
# Path & Frontend Configuration
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent

# Set up templates and statics to look inside your unified frontend directory
templates = Jinja2Templates(directory=str(BASE_DIR / "frontend" / "templates"))
app.mount("/static", StaticFiles(directory=str(BASE_DIR / "frontend" / "static")), name="static")


# --------------------------------------------------
# Frontend UI View Rendering Routes
# --------------------------------------------------

@app.get("/", response_class=HTMLResponse)
async def index_page(request: Request):
    """Renders the main platform introduction splash portal."""
    return templates.TemplateResponse(request=request, name="index.html")


@app.get("/login", response_class=HTMLResponse)
async def login_page(request: Request):
    """Renders the secure analyst authorization interface."""
    return templates.TemplateResponse(request=request, name="login.html")


@app.get("/dashboard", response_class=HTMLResponse)
async def dashboard_page(request: Request):
    """Renders the analytics directory tracking layout panel."""
    return templates.TemplateResponse(request=request, name="dashboard.html")


@app.get("/chat", response_class=HTMLResponse)
async def chat_workspace_page(request: Request):
    """Renders the dual split-pane agent workspace console."""
    return templates.TemplateResponse(request=request, name="chat.html")


# --------------------------------------------------
# Core Functional REST API Routes
# --------------------------------------------------

@app.post("/api/login")
async def handle_login(username: str = Form(...), password: str = Form(...)):
    """
    Handles internal user verification matching your frontend fetch signature.
    Simple sandbox confirmation: authenticates if username/password are provided.
    """
    if not username or not password:
        raise HTTPException(status_code=401, detail="Invalid analytical profile credentials.")
    
    # Simulates a successful login redirect cookie or session setup
    response = RedirectResponse(url="/dashboard", status_code=303)
    return response

@app.post("/api/chat", response_model=ChatResponse)
async def process_agent_query(request: ChatRequest):
    """
    Executes iterative processing loops against our core LangGraph agent graph executor.
    Captures the final AI message output and tool nodes from the graph state history.
    """
    try:
        prompt = request.message
        if request.client_id is not None:
            prompt = f"[Target Client Context ID: {request.client_id}] {prompt}"

        # Execute processing loop inside our singleton LangGraph executor
        # LangGraph returns the updated state containing a "messages" key
        response_data = financial_agent_executor.invoke({"messages": [("user", prompt)]})

        # 1. Extract the Final Answer from LangGraph's message state history
        final_output = "No response generated by agent configuration."
        graph_messages = response_data.get("messages", [])
        
        if graph_messages:
            # The last message in the state list is the agent's final text output
            final_output = graph_messages[-1].content

        # 2. Extract and map intermediate tool execution steps for your right panel log
        steps = []
        for msg in graph_messages:
            # Check if this message was an AI call requesting a tool execution
            if hasattr(msg, "tool_calls") and msg.tool_calls:
                for tool_call in msg.tool_calls:
                    steps.append(
                        AgentStep(
                            tool=tool_call.get("name", "Unknown Tool"),
                            tool_input=str(tool_call.get("args", "")),
                            log=f"Invoking tool framework with arguments: {tool_call.get('args')}"
                        )
                    )

        return ChatResponse(
            status="success",
            output=final_output,
            intermediate_steps=steps
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Agent Graph Execution Exception: {str(e)}")

# --------------------------------------------------
# Node Observability & Health Indicators
# --------------------------------------------------

@app.get("/health")
async def health_check():
    db_status = "disconnected"
    vector_store_status = "not_loaded"

    try:
        # Aligns strictly with data/meridian_wealth.db configuration
        db_path = BASE_DIR / "data" / "meridian_wealth.db"
        if db_path.exists():
            conn = sqlite3.connect(db_path)
            conn.close()
            db_status = "connected"
    except Exception:
        pass

    try:
        # Aligns precisely with your updated data/faiss_index pathing structures
        faiss_path = BASE_DIR / "data" / "faiss_index"
        if faiss_path.exists():
            vector_store_status = "loaded"
    except Exception:
        pass

    return {
        "status": "healthy",
        "agent": "ready",
        "database": db_status,
        "vector_store": vector_store_status
    }


@app.get("/agentinfo")
async def agent_info():
    return {
        "agent_name": "Financial Analyst Agent",
        "version": "1.0.0",
        "orchestration": "LangChain ReAct / LangGraph",
        "model": "gpt-4o-mini",
        "database": "SQLite",
        "vector_store": "FAISS Index Engine",
        "web_search": "Tavily Engine Integration",
        "tools": ["portfolio_lookup", "calculate_metrics", "policy_retriever", "tavily_search_results_json"]
    }


# Local Server Development Execution Execution Context
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)