from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class ChatRequest(BaseModel):
    client_id: Optional[int] = Field(None, description="Optional ID of the client being discussed")
    message: str = Field(..., description="The user query or instruction for the financial agent")

class AgentStep(BaseModel):
    tool: str = Field(..., description="The tool selected by the agent")
    tool_input: str = Field(..., description="The arguments passed to the tool")
    log: str = Field(..., description="The thought process log associated with this action")

class ChatResponse(BaseModel):
    status: str = Field("success", description="Status of the agent execution")
    output: str = Field(..., description="The final structured answer generated by the agent")
    intermediate_steps: List[AgentStep] = Field(default=[], description="The sequence of thoughts and tool executions")

class ClientPortfolioSummary(BaseModel):
    client_id: int
    name: str
    risk_profile: str
    total_aum: float
    holdings: List[Dict[str, Any]]